name: PR Checks
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install packages
        run: npm ci
      - name: Check format
        run: npm run format:check
